### ISSUE TITLE
Trouble with custom sections in the template

### ISSUE THREAD

**Issue by Fopje** [pwndoc/pwndoc#146]
I've went through the documentation and the issues (#134 / #65 ) made by other users about the custom sections, yet I keep having trouble getting it to work.

I decided to started simple, by just adding one section named testsubject with an input field. Then I just try to include the name of the section into the default template, resulting in error about a missing image tag in the paragraph (I did upload company logo as this gave an issue before #65 ).

Also chaging to the exact same contents of #65 gives the same result. No success with a HTML editor either.

![image](https://user-images.githubusercontent.com/4934752/123797698-bf63d280-d8e6-11eb-8468-80504a10641b.png)

```
pwndoc-backend-dev | Error: Raw tag not in paragraph
pwndoc-backend-dev |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend-dev |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:190:13)
pwndoc-backend-dev |     at expandOne (/app/node_modules/docxtemplater/js/traits.js:189:7)
pwndoc-backend-dev |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend-dev |     at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20) {
pwndoc-backend-dev |   properties: {
pwndoc-backend-dev |     id: 'raw_tag_outerxml_invalid',
pwndoc-backend-dev |     explanation: 'The tag "image" is not inside a paragraph',
pwndoc-backend-dev |     rootError: Error: No tag "w:t" was found at the left
pwndoc-backend-dev |         at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend-dev |         at throwXmlTagNotFound (/app/node_modules/docxtemplater/js/errors.js:138:13)
pwndoc-backend-dev |         at getLeft (/app/node_modules/docxtemplater/js/doc-utils.js:404:3)
pwndoc-backend-dev |         at expandOne (/app/node_modules/docxtemplater/js/traits.js:185:12)
pwndoc-backend-dev |         at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend-dev |         at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |         at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22) {
pwndoc-backend-dev |       properties: [Object]
pwndoc-backend-dev |     },
pwndoc-backend-dev |     xtag: 'image',
pwndoc-backend-dev |     offset: 687,
pwndoc-backend-dev |     postparsed: [
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object]
pwndoc-backend-dev |     ],
pwndoc-backend-dev |     expandTo: 'w:t',
pwndoc-backend-dev |     index: 0,
pwndoc-backend-dev |     file: 'word/document.xml'
pwndoc-backend-dev |   }
pwndoc-backend-dev | }
pwndoc-backend-dev | Error: Raw tag not in paragraph
pwndoc-backend-dev |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend-dev |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:190:13)
pwndoc-backend-dev |     at expandOne (/app/node_modules/docxtemplater/js/traits.js:189:7)
pwndoc-backend-dev |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend-dev |     at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend-dev |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |     at Array.reduce (<anonymous>)
pwndoc-backend-dev |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20) {
pwndoc-backend-dev |   properties: {
pwndoc-backend-dev |     id: 'raw_tag_outerxml_invalid',
pwndoc-backend-dev |     explanation: 'The tag "image" is not inside a paragraph',
pwndoc-backend-dev |     rootError: Error: No tag "w:t" was found at the left
pwndoc-backend-dev |         at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend-dev |         at throwXmlTagNotFound (/app/node_modules/docxtemplater/js/errors.js:138:13)
pwndoc-backend-dev |         at getLeft (/app/node_modules/docxtemplater/js/doc-utils.js:404:3)
pwndoc-backend-dev |         at expandOne (/app/node_modules/docxtemplater/js/traits.js:185:12)
pwndoc-backend-dev |         at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend-dev |         at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend-dev |         at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend-dev |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend-dev |         at Array.reduce (<anonymous>)
pwndoc-backend-dev |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22) {
pwndoc-backend-dev |       properties: [Object]
pwndoc-backend-dev |     },
pwndoc-backend-dev |     xtag: 'image',
pwndoc-backend-dev |     offset: 680,
pwndoc-backend-dev |     postparsed: [
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend-dev |       [Object], [Object], [Object]
pwndoc-backend-dev |     ],
pwndoc-backend-dev |     expandTo: 'w:t',
pwndoc-backend-dev |     index: 0,
pwndoc-backend-dev |     file: 'word/document.xml'
pwndoc-backend-dev |   }
pwndoc-backend-dev | }
```

![image](https://user-images.githubusercontent.com/4934752/123797962-06ea5e80-d8e7-11eb-8f5b-51f4a3c827de.png)

![image](https://user-images.githubusercontent.com/4934752/123798008-123d8a00-d8e7-11eb-86bd-0442838b6cfe.png)

![image](https://user-images.githubusercontent.com/4934752/123798041-1cf81f00-d8e7-11eb-83a9-a2f888801b43.png)

**Comment by Fopje** [comment]
Problem solved, I have to use the label as field.

![image](https://user-images.githubusercontent.com/4934752/124269190-ddc20c00-db3a-11eb-9fa7-8fadee50bd32.png)

![image](https://user-images.githubusercontent.com/4934752/124269238-ed415500-db3a-11eb-8675-b0c5307d3237.png)
