### ISSUE TITLE
Something went wrong contacting backend

### ISSUE THREAD

**Issue by asilhansahin** [pwndoc/pwndoc#189]
Hi,
When i build and run with sudo i am getting this error message. Outputs right there ;
O.S: Ubuntu 20.04.1 LTS Desktop

![alt text](https://i.hizliresim.com/lcqvzyq.jpg)
![alt text](https://i.hizliresim.com/3vobidm.jpg)
![alt text](https://i.hizliresim.com/56fng6c.jpg)

output log is there;

```
Attaching to pwndoc-backend
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_10_524Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_12_525Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_14_600Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_16_679Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_19_184Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_22_503Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_27_496Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_35_710Z-debug.log
pwndoc-backend     |
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     |
pwndoc-backend     | /app/src/models/settings.js:20
pwndoc-backend     |                 acilColor: { type: String, default: "#6a6a6a", validate: [colorValidator, 'Invalid color'] }
pwndoc-backend     |                 ^^^^^^^^^
pwndoc-backend     |
pwndoc-backend     | SyntaxError: Unexpected identifier
pwndoc-backend     |     at wrapSafe (internal/modules/cjs/loader.js:988:16)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1036:27)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Module.require (internal/modules/cjs/loader.js:961:19)
pwndoc-backend     |     at require (internal/modules/cjs/helpers.js:92:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:40:1)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:937:32)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
pwndoc-backend     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
pwndoc-backend     |     at internal/main/run_main_module.js:17:47
pwndoc-backend     | npm ERR! code ELIFECYCLE
pwndoc-backend     | npm ERR! errno 1
pwndoc-backend     | npm ERR! pwndoc-backend@0.0.1 start: `node src/app.js`
pwndoc-backend     | npm ERR! Exit status 1
pwndoc-backend     | npm ERR!
pwndoc-backend     | npm ERR! Failed at the pwndoc-backend@0.0.1 start script.
pwndoc-backend     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pwndoc-backend     |
pwndoc-backend     | npm ERR! A complete log of this run can be found in:
pwndoc-backend     | npm ERR!     /root/.npm/_logs/2021-09-23T12_26_50_449Z-debug.log
pwndoc-backend exited with code 1
```

Thanks in advance.

**Comment by asilhansahin** [comment]
I mıdified something. U're right. It was syntax problem. I solved right now. Thanks a lot ^^
