### ISSUE TITLE
Python Error when deploying a fresh pwndoc instance

### ISSUE THREAD

**Issue by Hax0rG1rl** [pwndoc/pwndoc#213]
Hi, 

I am trying to deploy a fresh pwndoc instance, 

Env: Ubuntu 20.04.3 | Latest docker.io | docker-compose v2.1.0

Repro steps: 

1. git clone the repo
2. docker-compose up -d --build

As a result, I get this error at the end that looks like a show stopper. 

```
 ---> 88f405a72005
Step 3/11 : WORKDIR /app
 ---> Using cache
 ---> 5d1683612bf4
Step 4/11 : COPY package*.json ./
 ---> Using cache
 ---> a5334099f56a
Step 5/11 : RUN apk --no-cache add --virtual builds-deps build-base python git
 ---> Running in a6cae06cdd40
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
**ERROR: unable to select packages:
  python (no such package):
    required by: builds-deps-20211111.001751[python]
1 error occurred:
        * Status: The command '/bin/sh -c apk --no-cache add --virtual builds-deps build-base python git' returned a non-zero code: 2, Code: 2**
 ```

Any ideas on how to fix this? 

Thanks!

**Comment by wannabeslime** [comment]
In my case, line 6 of the backend/Dockerfile,
I changed `RUN apk --no-cache add --virtual builds-deps build-base python git` to 
`RUN apk --no-cache add --virtual builds-deps build-base python3 git` and it worked.
But I don't know what side effects it will cause.

**Comment by Hax0rG1rl** [comment]
@wannabeslime , it worked that way but the backend logs displays other error messages: 

```
docker-compose logs -f pwndoc-backend
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | Initializing Settings
pwndoc-backend  | /app/node_modules/mongodb/lib/cmap/connection.js:261
pwndoc-backend  |           callback(new MongoError(document));
pwndoc-backend  |                    ^
pwndoc-backend  |
pwndoc-backend  | MongoError: a collection 'pwndoc.customsections' already exists
pwndoc-backend  |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:261:20)
pwndoc-backend  |     at MessageStream.emit (node:events:390:28)
pwndoc-backend  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
pwndoc-backend  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
pwndoc-backend  |     at writeOrBuffer (node:internal/streams/writable:389:12)
pwndoc-backend  |     at _write (node:internal/streams/writable:330:10)
pwndoc-backend  |     at MessageStream.Writable.write (node:internal/streams/writable:334:10)
pwndoc-backend  |     at Socket.ondata (node:internal/streams/readable:754:22)
pwndoc-backend  |     at Socket.emit (node:events:390:28)
pwndoc-backend  |     at addChunk (node:internal/streams/readable:315:12)
pwndoc-backend  |     at readableAddChunk (node:internal/streams/readable:289:9)
pwndoc-backend  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
pwndoc-backend  |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
pwndoc-backend  |   ok: 0,
pwndoc-backend  |   errmsg: "a collection 'pwndoc.customsections' already exists",
pwndoc-backend  |   code: 48,
pwndoc-backend  |   codeName: 'NamespaceExists',
pwndoc-backend  |   [Symbol(mongoErrorContextSymbol)]: {}
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | Initializing Settings
pwndoc-backend  | npm ERR! path /app
pwndoc-backend  | npm ERR! command failed
pwndoc-backend  | npm ERR! signal SIGTERM
pwndoc-backend  | npm ERR! command sh -c node src/app.js
pwndoc-backend  |
pwndoc-backend  | npm ERR! A complete log of this run can be found in:
pwndoc-backend  | npm ERR!     /root/.npm/_logs/2021-11-11T07_58_09_906Z-debug.log
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
```

**Comment by yeln4ts** [comment]
This issue was fixed in a recent merged.
@Hax0rG1rl try to redeploy a fresh instance, maybe there was an issue when building the database

**Comment by Hax0rG1rl** [comment]
Thank you!
