### ISSUE TITLE
Background color depends to field / customField

### ISSUE THREAD

**Issue by Rafityy** [pwndoc/pwndoc#238]
Hello, thank you for this amazing project. Is there any way to add background color to a field / customfield ? I saw the cvssColor variable but It only work for cvss severity. For example, if remediationComplexity == 'Easy' => put a green background.

**Comment by yeln4ts** [comment]
Maybe adding colors in the template data could achieve that.
Then you could do that directly in the template:
{#remediationComplexity == 0}
{@easyColor}
Easy
{/ remediationComplexity == 0}

But I would not do that for each field, since you could have infinite custom fields it would need to be a generic usage

**Comment by rayaar** [comment]
I would like to see this as well. I have a table of findings based on custom categories, and would like different colors if there is a finding or not.

**Comment by WhiteWinterWolf** [comment]
The easiest way IMHO would be to create a custom filter for this.

Look in the source code:
- How current filters are implemented, these are basically functions which consume an input and returns an output, leaving everything in between up to you ;
- How the CVSS severity color is implemented, these are basically just XML tags applying a background color style to the current cell.

This is really not as scary as it may seem. Once you have done that you should be able to create a filter which could take an integer as input, and generate the corresponding cell background color style XML tags as the output. Coloring the cell in your template would then be as simple as adding this at the beginning of your cell (`myCellColor` being your custom filter):

```
{@remediationComplexity | myCellColor}
```

**Comment by brunomcuesta** [comment]
Hello!
I'm trying to put a background color in a table cell depending on its value. The field is 'remediationComplexity'.

File;
/app/src/lib # vi report-generator.js

I tried adding the 'cellColor' attribute to the object, but it didn't work.

```
/** Colors for remediation complexity field */

var remediationLowColor = '4A86E8'; //default of blue 

var remediationMediumColor = 'f9a009'; //default of yellow

var remediationComplexColor = 'fe0000'; //default of red

var remediationCellLowColor = '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="'+remediationLowColor+'"/></w:tcPr>';

var remediationCellMediumColor = '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="'+remediationMediumColor+'"/></w:tcPr>';

var remediationCellComplexColor = '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="'+remediationComplexColor+'"/></w:tcPr>';



/** Return colors for remediation complexity cell table */

Object.assign(tmpFinding.remediationComplexity, { cellColor: "" }); // Attempting to add a cellColor attribute to the object

if (tmpFinding.remediationComplexity == "1") tmpFinding.remediationComplexity.cellColor = remediationCellLowColor

else if (tmpFinding.remediationComplexity == "2") tmpFinding.remediationComplexity.cellColor = remediationCellMediumColor

else if (tmpFinding.remedialComplexity == "3") tmpFinding.remediationComplexity.cellColor = remediationCellComplexColor

else tmpFinding.remediationComplexity.cellColor = cellNoneColor

```

The logs:

```
pwndoc-backend     | Error: Raw tag not in paragraph

pwndoc-backend     |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:21:16)

pwndoc-backend     |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:174:13)

pwndoc-backend     |     at getExpandLimit (/app/node_modules/docxtemplater/js/traits.js:229:7)

pwndoc-backend     |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:282:21)

pwndoc-backend     |     at RawXmlModule.postparse (/app/node_modules/docxtemplater/js/modules/rawxml.js:57:21)

pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:179:24

pwndoc-backend     |     at Array.reduce (<anonymous>)

pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:178:22)

pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:181:20)

pwndoc-backend     |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:221:30 {

pwndoc-backend     |   properties: {

pwndoc-backend     |     id: 'raw_tag_outerxml_invalid',

pwndoc-backend     |     explanation: 'The tag "remediationComplexity" is not inside a paragraph, putting raw tags inside an inline loop is disallowed.',

pwndoc-backend     |     rootError: Error: No tag "w:p" was found at the left

pwndoc-backend     |         at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:21:16)

pwndoc-backend     |         at throwXmlTagNotFound (/app/node_modules/docxtemplater/js/errors.js:119:13)

pwndoc-backend     |         at getLeft (/app/node_modules/docxtemplater/js/doc-utils.js:240:3)

pwndoc-backend     |         at getExpandLimit (/app/node_modules/docxtemplater/js/traits.js:225:12)

pwndoc-backend     |         at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:282:21)

pwndoc-backend     |         at RawXmlModule.postparse (/app/node_modules/docxtemplater/js/modules/rawxml.js:57:21)

pwndoc-backend     |         at /app/node_modules/docxtemplater/js/parser.js:179:24

pwndoc-backend     |         at Array.reduce (<anonymous>)

pwndoc-backend     |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:178:22)

pwndoc-backend     |         at postparse (/app/node_modules/docxtemplater/js/parser.js:181:20) {

pwndoc-backend     |       properties: [Object]

pwndoc-backend     |     },

pwndoc-backend     |     xtag: 'remediationComplexity',

pwndoc-backend     |     offset: 3679,

pwndoc-backend     |     postparsed: [

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object],

pwndoc-backend     |       [Object], [Object], [Object]

pwndoc-backend     |     ],

pwndoc-backend     |     expandTo: 'w:p',

pwndoc-backend     |     index: 14,

pwndoc-backend     |     file: 'word/document.xml'

pwndoc-backend     |   }

pwndoc-backend     | }


```

Apparently the error is:

`explanation: 'The tag "remediationComplexity" is not inside a paragraph, putting raw tags inside an inline loop is disallowed.',`

Template docx table cell:

```
{@remediationComplexity.cellColor}
{#remediationComplexity == ‘1’ }Low{/}{#remediationComplexity == ‘2’ }Medium{/}{#remediationComplexity == ‘3’ }Complex{/}
```

But I haven't figured out how to solve it.
Does anyone have any tips on how to add the color?
Thanks!

**Comment by brunomcuesta** [comment]
Solved!
I created filters to add color to the table cell background.
The first filter returns the color according to the integer value and the second when the value is a string.

In docker container:

`/app/src/lib # vi report-filters.js `

**Code**:

```

// Add color background in cell table with integer value            
expressions.filters.priorityColor = function(input) {                                                                                                    
    if (!input || input == "undefined") return input;                    
    if (input == '1') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="4A86E8"/></w:tcPr>';
    }                                                                                                                                                                         
    if (input == '2') {                                                                                                            
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="f9a009"/></w:tcPr>';                     
    }                                                             
    if (input == '3') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="fe0000"/></w:tcPr>';
   }                                                                                                                                                                                   
}   


// Add color background in cell table with string value            
expressions.filters.remediationColor = function(input) {                                                                                                    
    if (!input || input == "undefined") return input;                    
    if (input == 'Low') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="4A86E8"/></w:tcPr>';
    }                                                                                                                                                                         
    if (input == 'Medium') {                                                                                                            
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="f9a009"/></w:tcPr>';                     
    }                                                             
    if (input == 'High') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="fe0000"/></w:tcPr>';
   }                                                                                                                                                                                   
}   
```

In the template, use the tag to render the color in the table cell.


Probability cell:

```
{@probability  | probabilityColor}
{probability}

```

Remediation complexity cell:

```
{@remediationComplexity  | remediationColor}
{#remediationComplexity == ‘1’ }Low{/}{#remediationComplexity == ‘2’ }Medium{/}{#remediationComplexity == ‘3’ }Complex{/}
```

Restart docker container:

`docker restart <container_id>`

**Comment by UbaidAhmed2803** [comment]
Can we do the same for retestStatus? I tried the following but it didn't work:
 In the JS file added the following:

// Add color background in cell table with string value            
expressions.filters.retestStatus = function(input) {                                                                                                    
    if (!input || input == "undefined") return input;                    
    if (input == 'ko') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="4A86E8"/></w:tcPr>';
    }                                                                                                                                                                         
    if (input == 'ok') {                                                                                                            
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="f9a009"/></w:tcPr>';                     
    }                                                             
    if (input == 'partial') {                                                                 
        return '<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="fe0000"/></w:tcPr>';
   }                                                                                                                                                                                   
}

And in my template I was adding:
{@retestStatus | retestColor}
{#retestStatus==’’}NA{/}{#retestStatus==’ko’}Open{/}{#retestStatus==’ok’}Fixed{/}{#retestStatus==’unknown’}Not Verified{/}{#retestStatus==’partial’}Partially Fixed{/}

**Comment by brunomcuesta** [comment]
Hello!
You put the wrong name of the function you are going to use.

`expressions.filters.retestStatus <--- Must be retestColor`

And then you can use:

`{@retestStatus | retestColor}`
