### ISSUE TITLE
EACCESS permission denied in pwndoc-backend

### ISSUE THREAD

**Issue by se-fLa** [pwndoc/pwndoc#259]
On a fresh blank install on blank Ubuntu 20.04.3 LTS the pwndoc-backend fails to start due permission errors:

`
$ git clone https://github.com/pwndoc/pwndoc.git
$ cd pwndoc
$ docker-compose up -d --build
$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS                          PORTS                                               NAMES
6078e0161cb3   yeln4ts/pwndoc:backend    "npm start"              About a minute ago   Restarting (1) 13 seconds ago                                                       pwndoc-backend
ddad1a216d86   yeln4ts/pwndoc:frontend   "/docker-entrypoint.…"   About a minute ago   Up About a minute               80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp   pwndoc-frontend
ae3fba7846c4   mongo:4.2.15              "docker-entrypoint.s…"   About a minute ago   Up About a minute               127.0.0.1:27017->27017/tcp                          mongo-pwndoc
`

Gives the error:
`
$ docker-compose logs -f pwndoc-backend

pwndoc-backend     | > pwndoc-backend@0.0.1 start
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
pwndoc-backend     | node:internal/fs/utils:344
pwndoc-backend     |     throw err;
pwndoc-backend     |     ^
pwndoc-backend     | 
pwndoc-backend     | Error: EACCES: permission denied, open '/app/src/config/config.json'
pwndoc-backend     |     at Object.openSync (node:fs:585:3)
pwndoc-backend     |     at Object.writeFileSync (node:fs:2153:35)
pwndoc-backend     |     at Object.<anonymous> (/app/src/lib/auth.js:9:8)
pwndoc-backend     |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
pwndoc-backend     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
pwndoc-backend     |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend     |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend     |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend     |     at Object.<anonymous> (/app/src/models/user.js:6:12)
pwndoc-backend     |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
pwndoc-backend     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
pwndoc-backend     |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend     |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend     |     at require (node:internal/modules/cjs/helpers:102:18) {
pwndoc-backend     |   errno: -13,
pwndoc-backend     |   syscall: 'open',
pwndoc-backend     |   code: 'EACCES',
pwndoc-backend     |   path: '/app/src/config/config.json'
pwndoc-backend     | }
`

**Comment by paul1278** [comment]
In which folder did you execute `git clone`? Just tested it also on a fresh `Ubuntu 20.04.3 LTS`, no problem here.
Also could you please run `docker-compose exec pwndoc-backend ls -la /app/src/config/ && id` inside the cloned folder and paste the output, just in case something is off there?

**Comment by se-fLa** [comment]
I created a user "pwndoc" and executed the git clone it this users home directory. So the path of the clone is

`/home/pwndoc/pwndoc`

I'm tried running the docker-compose as booth user `pwndoc` and `root` - exactly same fault.

Could not run the command you requested since the container is restarting all the time, but started just the pwndoc-backend container and then could execute it, not sure if it affects the user?
Here is the output:

```
$ docker-compose exec pwndoc-backend ls -la /app/src/config/ && id 
total 16
drwxrwxr-x    2 nobody   nobody        4096 Feb  8 10:30 .
drwxrwxr-x    7 root     root          4096 Feb  8 10:30 ..
-rw-rw-r--    1 nobody   nobody         584 Feb  8 10:30 config.json
-rw-rw-r--    1 nobody   nobody         115 Feb  8 10:30 roles.json
uid=1001(pwndoc) gid=1001(pwndoc) groups=1001(pwndoc),117(docker)
```
