### ISSUE TITLE
Something went wrong contacting backend

### ISSUE THREAD

**Issue by FlyJanasic** [pwndoc/pwndoc#308]
### Steps and Logs
____________________________

I have tried to run pwndoc from a fresh install, but I ran into an issue contacting the backend. I started from a fresh install:

1. Downloaded the source code and ran `docker-compose up -d --build` and `docker-compose start`

2. Went to https://localhost:8443/login and met with the error.
![pwndoc error](https://user-images.githubusercontent.com/28174839/168953655-2382d0fe-06ef-4b48-a25d-eabd81f680e6.png)

Logs from `docker-compose logs -f pwndoc-backend`

```
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
pwndoc-backend  |
pwndoc-backend  | > pwndoc-backend@0.0.1 start
pwndoc-backend  | > node src/app.js
pwndoc-backend  |
pwndoc-backend  | node:internal/modules/cjs/loader:936
pwndoc-backend  |   throw err;
pwndoc-backend  |   ^
pwndoc-backend  |
pwndoc-backend  | Error: Cannot find module './config/config.json'
pwndoc-backend  | Require stack:
pwndoc-backend  | - /app/src/app.js
pwndoc-backend  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
pwndoc-backend  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
pwndoc-backend  |     at require (node:internal/modules/cjs/helpers:102:18)
pwndoc-backend  |     at Object.<anonymous> (/app/src/app.js:13:14)
pwndoc-backend  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
pwndoc-backend  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
pwndoc-backend  |     at Module.load (node:internal/modules/cjs/loader:981:32)
pwndoc-backend  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
pwndoc-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
pwndoc-backend  |   code: 'MODULE_NOT_FOUND',
pwndoc-backend  |   requireStack: [ '/app/src/app.js' ]
pwndoc-backend  | }
```

### Environment
____________________________
Browser: Firefox 100.0.1 (64-bit)
OS: Windows 10 Pro 21H1

Browser console logs:
```
Error: Request failed with status code 502
    exports https://localhost:8443/js/vendor.a1a08e7d.js:15
    exports https://localhost:8443/js/vendor.a1a08e7d.js:23
    onreadystatechange https://localhost:8443/js/vendor.a1a08e7d.js:67
[8.b01d0e40.js:1:6444](https://localhost:8443/js/8.b01d0e40.js)
Error: Promised response from onMessage listener went out of scope 7 [background.js:842:170](moz-extension://1b0ea06c-a820-454a-8028-9cd8d2afe009/dist/background.js)
XHRGEThttps://localhost:8443/socket.io/?EIO=3&transport=polling&t=O3LJgAj
[HTTP/1.1 502 Bad Gateway 3146ms]
```

**Comment by Singh212dab** [comment]
maybe some file is missing because of that you are getting this error

**Comment by FlyJanasic** [comment]
Unsure if that is the reason, since I assume the source code zip has all the necessary code to run it. I have used pwndoc before via the source code and had no issues.

Regardless, I used git clone and ran a fresh installation there. Here are the logs from docker-compose up -d --build if relevant.

```
[+] Building 18.2s (26/26) FINISHED
 => [yeln4ts/pwndoc:frontend internal] load build definition from Dockerfile                                       0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [yeln4ts/pwndoc:backend internal] load build definition from Dockerfile                                        0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [yeln4ts/pwndoc:frontend internal] load .dockerignore                                                          0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [yeln4ts/pwndoc:backend internal] load .dockerignore                                                           0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [yeln4ts/pwndoc:frontend internal] load metadata for docker.io/library/nginx:stable-alpine                     1.1s
 => [yeln4ts/pwndoc:backend internal] load metadata for docker.io/library/node:lts-alpine                          1.1s
 => [yeln4ts/pwndoc:backend internal] load build context                                                           0.0s
 => => transferring context: 2.91kB                                                                                0.0s
 => [yeln4ts/pwndoc:frontend build 1/6] FROM docker.io/library/node:lts-alpine@sha256:1a9a71ea86aad332aa7740316d4  0.0s
 => CACHED [yeln4ts/pwndoc:backend 2/7] RUN mkdir -p /app                                                          0.0s
 => CACHED [yeln4ts/pwndoc:backend 3/7] WORKDIR /app                                                               0.0s
 => CACHED [yeln4ts/pwndoc:backend 4/7] COPY package*.json ./                                                      0.0s
 => CACHED [yeln4ts/pwndoc:backend 5/7] RUN apk --no-cache add --virtual builds-deps build-base python3 git        0.0s
 => CACHED [yeln4ts/pwndoc:backend 6/7] RUN npm install                                                            0.0s
 => CACHED [yeln4ts/pwndoc:backend 7/7] COPY . .                                                                   0.0s
 => [yeln4ts/pwndoc:frontend] exporting to image                                                                   0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:6fa589193895b12f19660acfa8270d60940de4f649c267fecd23a0a62be7e58e                       0.0s
 => => naming to docker.io/yeln4ts/pwndoc:backend                                                                  0.0s
 => => writing image sha256:844a16efe851263b771cde36a49d219ec44c4423a90ffccad89b47be47facd52                       0.0s
 => => naming to docker.io/yeln4ts/pwndoc:frontend                                                                 0.0s
 => [yeln4ts/pwndoc:frontend stage-1 1/5] FROM docker.io/library/nginx:stable-alpine@sha256:016789c9a2d021b2dcb5e  0.0s
 => [yeln4ts/pwndoc:frontend internal] load build context                                                          0.1s
 => => transferring context: 2.28MB                                                                                0.1s
 => CACHED [yeln4ts/pwndoc:frontend build 2/6] WORKDIR /app                                                        0.0s
 => CACHED [yeln4ts/pwndoc:frontend build 3/6] COPY package.json ./                                                0.0s
 => CACHED [yeln4ts/pwndoc:frontend build 4/6] RUN npm install                                                     0.0s
 => [yeln4ts/pwndoc:frontend build 5/6] COPY . .                                                                   0.0s
 => [yeln4ts/pwndoc:frontend build 6/6] RUN npm run build                                                         16.8s
 => CACHED [yeln4ts/pwndoc:frontend stage-1 2/5] COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf            0.0s
 => CACHED [yeln4ts/pwndoc:frontend stage-1 3/5] RUN mkdir -p /etc/nginx/ssl                                       0.0s
 => CACHED [yeln4ts/pwndoc:frontend stage-1 4/5] COPY ssl/server* /etc/nginx/ssl/                                  0.0s
 => CACHED [yeln4ts/pwndoc:frontend stage-1 5/5] COPY --from=build /app/dist/spa /usr/share/nginx/html             0.0s
[+] Running 4/4
 - Network pwndoc_backend     Created                                                                              0.1s
 - Container pwndoc-frontend  Started                                                                              2.8s
 - Container mongo-pwndoc     Started                                                                              3.0s
 - Container pwndoc-backend   Started                                                                              3.9s
```

**Comment by yeln4ts** [comment]
Did you solve your issue ?
It seems indeed linked to the missing file config.js

**Comment by FlyJanasic** [comment]
Unsure what the fix was, but a clean installation again and it worked. Closing the problem as it is no longer an issue.

**Comment by VestaCord** [comment]
Having the exact same issue, reattempted clean install as well...
