### ISSUE TITLE
[bug]tiptap-extensions throw error "Duplicate use of selection JSON ID cell"

### ISSUE THREAD

**Issue by Monyer** [pwndoc/pwndoc#325]
When running "docker-compose -f frontend/docker-compose.dev.yml up -d --build" at the first time, 
then visit https://127.0.0.1:8081/vulnerabilities ,
browser throw an error and the page keep blank :

`vue-router.esm.js?85f8:2314 RangeError: Duplicate use of selection JSON ID cell
    at Function.jsonID (index.es.js?ed9c:188:1)
    at eval (index.es.js?d5b1:582:1)
    at ./node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js (vendor.js:6908:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (extensions.esm.js?6301:1:1)
    at ./node_modules/tiptap-extensions/dist/extensions.esm.js (vendor.js:6896:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/components/editor.vue?vue&type=script&lang=js&:15:75)`

This error was talked at:
https://github.com/ueberdosis/tiptap/issues/316

The reason is :
Folder .../node_modules/ contains subfolder '/prosemirror-tables' (version 1.1.1)
Folder .../node_modules/tiptap-extensions/node-modules/ contains subfolder '/prosemirror-tables' (version 1.0.0)
Loading duplicated modules with different versions raises the error.

So my temporary way to fix it was rename .../node_modules/tiptap-extensions/node-modules to .../node_modules/tiptap-extensions/node-modules--

I didn't find a normal to fix it.

**Comment by ismail-raslan** [comment]
Kindly modify those 2 lines to be:
"tiptap": "^1.32.2",
"tiptap-extensions": "^1.35.2",
 and add those to you package.json file,
"@tiptap/core": "^2.0.0-beta.182",
"@tiptap/starter-kit": "^2.0.0-beta.191",
 rebuild and Voalaaa

**Comment by Mikaleb** [comment]
And it doesn't work in v1 !

**Comment by yeln4ts** [comment]
I could not reproduce this issue when building from scratch.
When inspecting the container I only have one `prosemirror-tables` module installed.
![image](https://user-images.githubusercontent.com/4255028/182161118-9b5623ec-9cd6-4244-905f-42998a20063c.png)
![image](https://user-images.githubusercontent.com/4255028/182161208-48fff710-7212-4d62-9535-9105cc584609.png)

**Comment by nobox910** [comment]
@Monyer : I fixed issues by switching to yarn (frontend/docker-compose.dev.yml)

**Comment by Monyer** [comment]
> @Monyer : I fixed issues by switching to yarn (frontend/docker-compose.dev.yml)

This issue can be fixed.

**Comment by yeln4ts** [comment]
I would need to be able to reproduce in order to fix the issue.
I don't know the impact of switching from npm to yarn.
Can you tell what OS you use ? Did you try to delete your docker containers and images and retry from scratch ?

**Comment by nobox910** [comment]
tamqm@runner:~/pwndoc$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

tamqm@runner:~/pwndoc$ docker --version
Docker version 20.10.16, build aa7e414

![2022-08-10_16-26-26](https://user-images.githubusercontent.com/58721688/183866847-4d93b8fd-2873-482b-8f68-998bc1d8c560.png)

![2022-08-10_16-27-40](https://user-images.githubusercontent.com/58721688/183866892-4b84e20a-8ed9-4024-84d3-555936575426.png)

**Comment by yeln4ts** [comment]
I installed a fresh Ubuntu system, cloned the repo and built the containers and did not have that error (tried both prod and dev)
![image](https://user-images.githubusercontent.com/4255028/183996481-6599474f-f4a9-44c7-b6d8-ec8c58f2ddd9.png)

Can you try using a fresh cloned repository of pwndoc ? Maybe it's an issue with a package.json lock file
