### ISSUE TITLE
"Register First User" button doesn't do anything

### ISSUE THREAD

**Issue by itayfunes** [pwndoc/pwndoc#368]
Whenever I try to create my first admin user, I type all the information needed and it doesn't give me any error, I click on the button and it doesn't do anything, no error pops up, nothing, I tried installing on a different device, same problem, tried multiple browsers, nothing. I followed the documentation.

**Comment by Sorrow81** [comment]
Do you have error in your developper console ? (type F12 and go in console tab)

**Comment by itayfunes** [comment]
Actually, yes:

`vendor.b1f48622.js:38 ReferenceError: utils is not defined
    at s.initUser (8.04f9d5a3.js:1:6832)
    at click (8.04f9d5a3.js:1:2573)
    at On (vendor.b1f48622.js:38:25502)
    at s.n (vendor.b1f48622.js:38:9521)
    at On (vendor.b1f48622.js:38:25502)
    at Ye.t.$emit (vendor.b1f48622.js:38:20163)
    at s.click (vendor.b1f48622.js:32:22800)
    at On (vendor.b1f48622.js:38:25502)
    at HTMLButtonElement.n (vendor.b1f48622.js:38:9521)
    at o._wrapper (vendor.b1f48622.js:38:62440)`

**Comment by itayfunes** [comment]
Thank you, worked!
