### ISSUE TITLE
Something went wrong contacting backend

### ISSUE THREAD

**Issue by PinkDev1** [pwndoc/pwndoc#43]
## Replicate issue

Fresh install:

1. git clone https://github.com/pwndoc/pwndoc
2. cd pwndoc
3. sudo docker-compose up -d --build
4. sudo docker-compose start
5. Browse https://localhost:4242/api/users/init and wait for it to finish loading the JSON (`{"status":"success","datas":true}`)
6. Browse https://localhost:8443/

## Error
"Something went wrong contacting backend"

![Kali-Linux-2020 1-vmware-amd64-2020-10-30-20-24-27](https://user-images.githubusercontent.com/46269721/97764609-1bcbe380-1b07-11eb-99a8-aa49bcda6791.png)

## Environment

Browser: Firefox 82.0.1 (64-bit)
OS: 5.8.0-kali3-amd64
docker-compose version 1.25.0, build unknown
Docker version 19.03.13, build 4484c46

## Logs:
```
Attaching to pwndoc-backend
pwndoc-backend     | 
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
pwndoc-backend     | 
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
pwndoc-backend     | 
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
pwndoc-backend     | (node:27) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo-pwndoc mongo-pwndoc:27017
pwndoc-backend     |     at new MongooseServerSelectionError (/app/node_modules/mongoose/lib/error/serverSelection.js:24:11)
pwndoc-backend     |     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:823:32)
pwndoc-backend     |     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:333:15)
pwndoc-backend     |     at Object.<anonymous> (/app/src/app.js:20:10)
pwndoc-backend     |     at Module._compile (internal/modules/cjs/loader.js:689:30)
pwndoc-backend     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
pwndoc-backend     |     at Module.load (internal/modules/cjs/loader.js:599:32)
pwndoc-backend     |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
pwndoc-backend     |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
pwndoc-backend     |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
pwndoc-backend     |     at startup (internal/bootstrap/node.js:283:19)
pwndoc-backend     |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
pwndoc-backend     | (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
pwndoc-backend     | (node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Browser console logs

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4242/socket.io/?EIO=3&transport=polling&t=NLxrk90. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4242/api/users/init. (Reason: CORS request did not succeed).

Error: Network Error
    exports https://127.0.0.1:8443/js/vendor.01e92452.js:15
    onerror https://127.0.0.1:8443/js/vendor.01e92452.js:63
8.9094a047.js:1:4736
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4242/socket.io/?EIO=3&transport=polling&t=NLxrkTK. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4242/socket.io/?EIO=3&transport=polling&t=NLxrlK0. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4242/socket.io/?EIO=3&transport=polling&t=NLxrl-C. (Reason: CORS request did not succeed).
```

![image](https://user-images.githubusercontent.com/46269721/97764787-ad3b5580-1b07-11eb-9b69-8a1a32c30617.png)

Every 6~ seconds it throws another CORS error.
I'm not entirely sure as to why this happened, but my _guess_ is that the certificate exception for the backend wasn't added correctly.
I also tested it on a default Firefox profile, but exactly the same ocurrs.

**Comment by yeln4ts** [comment]
This is because you added certificate exception for localhost:4242 and now you are using 127.0.0.1 which the browser don't have exception for.
You simply have to go to https://127.0.0.1:4242 and add exception like you did for localhost.

**Comment by PinkDev1** [comment]
Thanks! That worked!
Consider adding this warning to the docs
