### ISSUE TITLE
template issue - reuploading of improve template not working

### ISSUE THREAD

**Issue by rahultalekar** [pwndoc/pwndoc#461]
Everytime need to create new report which is time consuming.

why updated templated is not working giving below error

Error: Raw tag not in paragraph
pwndoc-backend  |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:21:16)
pwndoc-backend  |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:174:13)
pwndoc-backend  |     at getExpandLimit (/app/node_modules/docxtemplater/js/traits.js:229:7)
pwndoc-backend  |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:282:21)
pwndoc-backend  |     at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend  |     at /app/node_modules/docxtemplater/js/parser.js:179:24
pwndoc-backend  |     at Array.reduce (<anonymous>)
pwndoc-backend  |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:178:22)
pwndoc-backend  |     at postparse (/app/node_modules/docxtemplater/js/parser.js:181:20)
pwndoc-backend  |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:221:30 {
pwndoc-backend  |   properties: {
pwndoc-backend  |     id: 'raw_tag_outerxml_invalid',
pwndoc-backend  |     explanation: 'The tag "image" is not inside a paragraph',
pwndoc-backend  |     rootError: Error: No tag "w:t" was found at the left
pwndoc-backend  |         at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:21:16)
pwndoc-backend  |         at throwXmlTagNotFound (/app/node_modules/docxtemplater/js/errors.js:119:13)
pwndoc-backend  |         at getLeft (/app/node_modules/docxtemplater/js/doc-utils.js:240:3)
pwndoc-backend  |         at getExpandLimit (/app/node_modules/docxtemplater/js/traits.js:225:12)
pwndoc-backend  |         at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:282:21)
pwndoc-backend  |         at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend  |         at /app/node_modules/docxtemplater/js/parser.js:179:24
pwndoc-backend  |         at Array.reduce (<anonymous>)
pwndoc-backend  |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:178:22)
pwndoc-backend  |         at postparse (/app/node_modules/docxtemplater/js/parser.js:181:20) {
pwndoc-backend  |       properties: [Object]
pwndoc-backend  |     },
pwndoc-backend  |     xtag: 'image',
pwndoc-backend  |     offset: 9456,
pwndoc-backend  |     postparsed: [
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object],
pwndoc-backend  |       [Object], [Object], [Object]
pwndoc-backend  |     ],
pwndoc-backend  |     expandTo: 'w:t',
pwndoc-backend  |     index: 0,
pwndoc-backend  |     file: 'word/document.xml'
pwndoc-backend  |   }
pwndoc-backend  | }

please anyone help me to resolve this issue

**Comment by rahultalekar** [comment]
anyone respond please

**Comment by Zeecka** [comment]
In your error message you got `explanation: 'The tag "image" is not inside a paragraph',`.
Does it work without the `image`/`images`tag ?
Is your `{%image}` inside a `{-w:p images}{/images}` tag ? (see https://pwndoc.github.io/pwndoc/#/docxtemplate?id=html-values-from-text-editors) ?
