### ISSUE TITLE
Cell Color On The Basis Of Retest Status

### ISSUE THREAD

**Issue by UbaidAhmed2803** [pwndoc/pwndoc#501]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to color-code the cell in my report for reassessment or retest. I am able to write the retest status using the following:
{#retestStatus==’ko’}Open{/retestStatus==’ko’}{#retestStatus==’ok’}Fixed{/retestStatus==’ok’}{#retestStatus==’unknown’}Not Verified{/retestStatus==’unknown’}{#retestStatus==’partial’}Partially Fixed{/retestStatus==’partial’}

Next what I want to do is change the background of this particular cell in the table to Red, Orange or Green in case the status is Open, Partially Fixed, and Fixed respectively.

--

</div></b> 

**Describe the solution you'd like**
Just like we have {@cvss.cellColor}, can't we have something similar for these statuses as well?

**Comment by UbaidAhmed2803** [comment]
Yes tried that as well but report generation fails and I get to see the below line in logs:

`"rootError": {
pwndoc-backend  |           "stack": "Error: Filter 'retestColor' is not defined\n    at isStateless (/app/node_modules/angular-expressions/lib/parse.js:2905:9)\n    at findConstantAndWatchExpressions (/app/node_modules/angular-expressions/lib/parse.js:2967:7)\n    at /app/node_modules/angular-expressions/lib/parse.js:2918:5\n    at forEach (/app/node_modules/angular-expressions/lib/parse.js:324:15)\n    at findConstantAndWatchExpressions (/app/node_modules/angular-expressions/lib/parse.js:2917:4)\n    at ASTCompiler.compile (/app/node_modules/angular-expressions/lib/parse.js:3078:3)\n    at Parser.parse (/app/node_modules/angular-expressions/lib/parse.js:4205:27)\n    at Object.compile (/app/node_modules/angular-expressions/lib/main.js:54:40)\n    at angularParser (/app/src/lib/report-generator.js:126:30)\n    at Render.parser (/app/src/lib/report-generator.js:163:12)",`
