### ISSUE TITLE
Custom Section image inclusion

### ISSUE THREAD

**Issue by x3lq** [pwndoc/pwndoc#79]
When creating a custom section with images, the text can be inserted but as soon as an image is added the template fails to be created.

It looks like the following in the frontend 
![image](https://user-images.githubusercontent.com/19569920/105723693-5dfa9a80-5f27-11eb-8d0f-2fdbf506af06.png)

In the word template itself it looks like the following:
<img width="366" alt="Bildschirmfoto 2021-01-25 um 16 10 56" src="https://user-images.githubusercontent.com/19569920/105724329-06106380-5f28-11eb-84ab-f66ee2bd53c2.png">

As I couldn't figure out how you start a paragraph, which should be the following:
`{#cleanup}{/cleanup}`
I am not sure if this helps the problem. 

The backend-logs are reporting the following:
`Error:

{ TypeError: Cannot read property '0' of undefined
    at ImageModule.getRenderedPart (/app/node_modules/docxtemplater-image-module-free/js/index.js:180:54)
    at ImageModule.render (/app/node_modules/docxtemplater-image-module-free/js/index.js:134:17)
    at moduleRender (/app/node_modules/docxtemplater/js/render.js:14:30)
    at /app/node_modules/docxtemplater/js/render.js:44:26
    at Array.map (<anonymous>)
    at Object.render (/app/node_modules/docxtemplater/js/render.js:42:24)
    at loopOver (/app/node_modules/docxtemplater/js/modules/loop.js:305:35)
    at ScopeManager.functorIfInverted (/app/node_modules/docxtemplater/js/scope-manager.js:159:9)
    at ScopeManager.loopOverValue (/app/node_modules/docxtemplater/js/scope-manager.js:184:16)
    at ScopeManager.loopOver (/app/node_modules/docxtemplater/js/scope-manager.js:153:19)
    at LoopModule.render (/app/node_modules/docxtemplater/js/modules/loop.js:334:39)
    at moduleRender (/app/node_modules/docxtemplater/js/render.js:14:30)
    at /app/node_modules/docxtemplater/js/render.js:44:26
    at Array.map (<anonymous>)
    at Object.render (/app/node_modules/docxtemplater/js/render.js:42:24)
    at loopOver (/app/node_modules/docxtemplater/js/modules/loop.js:305:35) properties: { file: 'word/document.xml' } }
`

Could you please add some clarity wether you need the paragraph or not and if so what it should be. 
Furthermore investigating the issue would be great, if I can be of any further assistance please say so

Kindest regards

**Comment by yeln4ts** [comment]
There is a description for HTML data in the doc: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=html-values-from-text-editors

You have to add a paragraph after {%images}

**Comment by nobox910** [comment]
@x3lq let try below
{-w:p cleanup.text}{@text | convertHTML}
                                            {-w:p images}{%image}
                                    Image 1 - {caption}{/images}{/cleanup.text}

{%image} without 's'

**Comment by x3lq** [comment]
Okay so we got it working. 

In the end our issues were that we didn't close the paragraph, which caused the original issue.
Yet it works for us with 
`{%image} `and NOT with `{%images}` as it states in the documentation.
This might be an issue and maybe needs a fix in the Documentation.

Our working solution looks like the following:
<img width="301" alt="Bildschirmfoto 2021-01-27 um 09 55 09" src="https://user-images.githubusercontent.com/19569920/105967149-d2e3e680-6085-11eb-811e-17fd10f40a1d.png">

Thank you all for you help 👍

**Comment by yeln4ts** [comment]
Updated documentation
